language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"

before_install:
  - mkdir node_modules
  - git clone https://github.com/jcoglan/vault-cipher.git node_modules/vault-cipher
