#!/usr/bin/env bash

if [ -n "$BASH_VERSION" ]; then
  root="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
  source "$root/completion.bash"

elif [ -n "$ZSH_VERSION" ]; then
  root="$(dirname "$(readlink -f "$0")")"
  source "$root/completion.zsh"
fi

