#!/usr/bin/env node

[ '*********************************'
, '* IMPORTANT UPGRADE INFORMATION *'
, '*********************************'
, ''
, 'If you are upgrading from Vault 0.2.0, the encryption format of the .vault'
, 'file has changed. You need to migrate this file to the new format as follows.'
, ''
, 'Make sure you make a backup copy of your .vault file first, and set'
, 'VAULT_PATH and VAULT_KEY appropriately for your config file. Then run:'
, ''
, '    npm uninstall -g vault'
, '    npm install -g vault@0.2.0'
, '    vault --export vault_config.json'
, '    npm update -g vault'
, '    vault --import vault_config.json'
, ''
, 'PLEASE make a backup of your .vault file before doing this, and post on the'
, 'mailing list if you have questions.'
, ''
, '    https://groups.google.com/group/vault-users'
, ''
]
.forEach(function(line) {
  console.log(line);
});

